-- user_score_history는 append-only 감사 원장이라 유저가 늘수록 가장 빨리 커지는 테이블이다.
-- created_at 기준 월별 range 파티션으로 나눠서 오래된 데이터 조회/보관이 최근 파티션에 영향을
-- 주지 않게 한다 (docs/scaling.md 3단계 참고).
--
-- Postgres 파티션 테이블은 PK/UNIQUE 인덱스가 파티션 키(created_at)를 포함해야 해서
-- PRIMARY KEY가 (id)에서 (id, created_at) 복합키로 바뀐다. 이 테이블은 id로 단건 조회하는
-- 코드 경로가 없어(JpaRepository<UserScoreHistory, Long> 기본 메서드만 사용, findById 미사용)
-- 애플리케이션 영향은 없다.

ALTER TABLE user_score_history RENAME TO user_score_history_old;
ALTER INDEX idx_score_history_user_id RENAME TO idx_score_history_user_id_old;

CREATE TABLE user_score_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    target     VARCHAR(10) NOT NULL DEFAULT 'SCORE',
    delta      INT         NOT NULL,
    reason     VARCHAR(50) NOT NULL,
    review_id  BIGINT      REFERENCES reviews (id),
    created_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE INDEX idx_score_history_user_id ON user_score_history (user_id);

-- 이번 달 기준 앞뒤로 몇 개월치 파티션을 미리 만들어둔다. 이후 파티션은 운영 배치(cron)로
-- 매달 추가해야 한다 — 이 마이그레이션은 초기 전환만 다룬다.
CREATE TABLE user_score_history_2026_06 PARTITION OF user_score_history
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE user_score_history_2026_07 PARTITION OF user_score_history
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE user_score_history_2026_08 PARTITION OF user_score_history
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE user_score_history_2026_09 PARTITION OF user_score_history
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
-- 파티션 범위를 벗어나는 값(과거 데이터, 파티션 생성을 깜빡한 미래 달)을 위한 안전망.
CREATE TABLE user_score_history_default PARTITION OF user_score_history DEFAULT;

INSERT INTO user_score_history (id, user_id, target, delta, reason, review_id, created_at)
    SELECT id, user_id, target, delta, reason, review_id, created_at FROM user_score_history_old;

SELECT setval(
    pg_get_serial_sequence('user_score_history', 'id'),
    COALESCE((SELECT MAX(id) FROM user_score_history), 1)
);

DROP TABLE user_score_history_old;
